"""empty message

Revision ID: e2f95fbcfb9f
Revises: 
Create Date: 2019-12-22 14:43:22.921456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f95fbcfb9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Client', sa.Column('token_instagram', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Client', 'token_instagram')
    # ### end Alembic commands ###
